name: Check ESLint on Pull Request

on:
  pull_request:
    branches: [main]
  push:
    branches: [development]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: installing eslint
        run: npm i 
      - name: Fixing Files
        run: npm run lint